export const WEEK_DAYS: Object[] = [
    { text: "Sunday", value: 0 },
    { text: "Monday", value: 1 },
    { text: "Tuesday", value: 2 },
    { text: "Wednesday", value: 3 },
    { text: "Thursday", value: 4 },
    { text: "Friday", value: 5 },
    { text: "Saturday", value: 6 },
  ];

export const TIMEZONE_DATA: Object[] = [
    { text: "UTC -12:00", value: "Etc/GMT+12" },
    { text: "UTC -11:00", value: "Etc/GMT+11" },
    { text: "UTC -10:00", value: "Etc/GMT+10" },
    { text: "UTC -09:00", value: "Etc/GMT+9" },
    { text: "UTC -08:00", value: "Etc/GMT+8" },
    { text: "UTC -07:00", value: "Etc/GMT+7" },
    { text: "UTC -06:00", value: "Etc/GMT+6" },
    { text: "UTC -05:00", value: "Etc/GMT+5" },
    { text: "UTC -04:00", value: "Etc/GMT+4" },
    { text: "UTC -03:00", value: "Etc/GMT+3" },
    { text: "UTC -02:00", value: "Etc/GMT+2" },
    { text: "UTC -01:00", value: "Etc/GMT+1" },
    { text: "UTC +00:00", value: "Etc/GMT" },
    { text: "UTC +01:00", value: "Etc/GMT-1" },
    { text: "UTC +02:00", value: "Etc/GMT-2" },
    { text: "UTC +03:00", value: "Etc/GMT-3" },
    { text: "UTC +04:00", value: "Etc/GMT-4" },
    { text: "UTC +05:00", value: "Etc/GMT-5" },
    { text: "UTC +05:30", value: "Asia/Calcutta" },
    { text: "UTC +06:00", value: "Etc/GMT-6" },
    { text: "UTC +07:00", value: "Etc/GMT-7" },
    { text: "UTC +08:00", value: "Etc/GMT-8" },
    { text: "UTC +09:00", value: "Etc/GMT-9" },
    { text: "UTC +10:00", value: "Etc/GMT-10" },
    { text: "UTC +11:00", value: "Etc/GMT-11" },
    { text: "UTC +12:00", value: "Etc/GMT-12" },
    { text: "UTC +13:00", value: "Etc/GMT-13" },
    { text: "UTC +14:00", value: "Etc/GMT-14" },
  ];

export const TIMESLOT_DURATION: Object[] = [
    { Name: "0.5 hour", Value: 30 },
    { Name: "1 hour", Value: 60 },
    { Name: "1.5 hours", Value: 90 },
    { Name: "2 hours", Value: 120 },
    { Name: "2.5 hours", Value: 150 },
    { Name: "3 hours", Value: 180 },
    { Name: "3.5 hours", Value: 210 },
    { Name: "4 hours", Value: 240 },
    { Name: "4.5 hours", Value: 270 },
    { Name: "5 hours", Value: 300 },
    { Name: "5.5 hours", Value: 330 },
    { Name: "6 hours", Value: 360 },
    { Name: "6.5 hours", Value: 390 },
    { Name: "7 hours", Value: 420 },
    { Name: "7.5 hours", Value: 450 },
    { Name: "8 hours", Value: 480 },
    { Name: "8.5 hours", Value: 510 },
    { Name: "9 hours", Value: 540 },
    { Name: "9.5 hours", Value: 570 },
    { Name: "10 hours", Value: 600 },
    { Name: "10.5 hours", Value: 630 },
    { Name: "11 hours", Value: 660 },
    { Name: "11.5 hours", Value: 690 },
    { Name: "12 hours", Value: 720 },
  ];

export const SCHEDULER_TRANSLATIONS = {
    "fr-CH": {
      schedule: {
        day: "ngày",
        week: "Tuần",
        workWeek: "Tuần làm việc",
        month: "tháng",
        agenda: "Chương trình nghị sự",
        weekAgenda: "Chương trình nghị sự tuần",
        workWeekAgenda: "Chương trình làm việc trong tuần",
        monthAgenda: "Chương trình nghị sự tháng",
        today: "Hôm nay",
        noEvents: "Không có sự kiện",
        emptyContainer: "Không có sự kiện theo lịch trình vào ngày này.",
        allDay: "Cả ngày",
        start: "Khởi đầu",
        end: "Kết thúc",
        more: "hơn",
        close: "Gần",
        cancel: "Hủy bỏ",
        noTitle: "(Không tiêu đề)",
        delete: "Xóa bỏ",
        deleteEvent: "Xóa sự kiện",
        deleteMultipleEvent: "Xóa nhiều sự kiện",
        selectedItems: "Các mục được chọn",
        deleteSeries: "Xóa sê-ri",
        edit: "Chỉnh sửa",
        editSeries: "Chỉnh sửa sê-ri",
        editEvent: "Chỉnh sửa sự kiện",
        createEvent: "Tạo nên",
        subject: "Môn học",
        addTitle: "Thêm tiêu đề",
        moreDetails: "Thêm chi tiết",
        save: "Tiết kiệm",
        editContent: "Bạn có muốn chỉnh sửa chỉ sự kiện này hoặc toàn bộ loạt?",
        deleteRecurrenceContent:
          "Bạn có muốn xóa chỉ sự kiện này hoặc toàn bộ loạt?",
        deleteContent: "Bạn có chắc chắn muốn xóa sự kiện này?",
        deleteMultipleContent: "Bạn có chắc chắn muốn xóa các sự kiện đã chọn?",
        newEvent: "Sự kiện mới",
        title: "Chức vụ",
        location: "Vị trí",
        description: "Sự miêu tả",
        timezone: "Múi giờ",
        startTimezone: "Bắt đầu múi giờ",
        endTimezone: "Múi giờ kết thúc",
        repeat: "Nói lại",
        saveButton: "Tiết kiệm",
        cancelButton: "Hủy bỏ",
        deleteButton: "Xóa bỏ",
        recurrence: "Sự tái xuất",
        wrongPattern: "Mẫu tái phát không hợp lệ.",
        seriesChangeAlert:
          "Các thay đổi được thực hiện cho các phiên bản cụ thể của chuỗi này sẽ bị hủy và các sự kiện đó sẽ khớp với chuỗi đó một lần nữa.",
        createError:
          "Thời gian của sự kiện phải ngắn hơn tần suất xảy ra. Rút ngắn thời lượng hoặc thay đổi mẫu lặp lại trong trình chỉnh sửa sự kiện lặp lại.",
        recurrenceDateValidation:
          "Một số tháng có ít hơn ngày đã chọn. Đối với những tháng này, sự xuất hiện sẽ rơi vào ngày cuối cùng của tháng.",
        sameDayAlert:
          "Hai lần xuất hiện của cùng một sự kiện không thể xảy ra trong cùng một ngày.",
        editRecurrence: "Chỉnh sửa tái phát",
        repeats: "Lặp lại",
        alert: "Thông báo",
        startEndError: "Ngày kết thúc được chọn xảy ra trước ngày bắt đầu.",
        invalidDateError: "Giá trị ngày nhập không hợp lệ.",
        ok: "Được",
        occurrence: "Xảy ra",
        series: "Loạt",
        previous: "Trước",
        next: "Kế tiếp",
        timelineDay: "Ngày thời gian",
        timelineWeek: "Tuần thời gian",
        timelineWorkWeek: "Tuần làm việc",
        timelineMonth: "Mốc thời gian",
      },
      recurrenceeditor: {
        none: "không ai",
        daily: "hằng ngày",
        weekly: "Hàng tuần",
        monthly: "Hàng tháng",
        month: "tháng",
        yearly: "Hàng năm",
        never: "Không bao giờ",
        until: "Cho đến khi",
        count: "Đếm",
        first: "Đầu tiên",
        second: "Thứ hai",
        third: "Thứ ba",
        fourth: "Thứ tư",
        last: "Cuối cùng",
        repeat: "Nói lại",
        repeatEvery: "Lặp lại mỗi",
        on: "Lặp lại trên",
        end: "Kết thúc",
        onDay: "ngày",
        days: "Ngày",
        weeks: "Tuần",
        months: "Tháng)",
        years: "Năm",
        every: "mỗi",
        summaryTimes: "thời gian",
        summaryOn: "trên",
        summaryUntil: "cho đến khi",
        summaryRepeat: "Lặp lại",
        summaryDay: "ngày",
        summaryWeek: "tuần",
        summaryMonth: "tháng)",
        summaryYear: "năm",
        monthWeek: "Tháng tuần",
        monthPosition: "Vị trí tháng",
        monthExpander: "Mở rộng tháng",
        yearExpander: "Mở rộng năm",
        repeatInterval: "Khoảng lặp lại",
      },
    },
  }